name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

  schedule:
    - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 18

      - run: echo ${{ hashFiles('yarn.lock') }}

      - name: Cache node modules
        uses: actions/cache@v2.0.0
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-

  test_output:
    runs-on: ubuntu-latest

    steps:
      - id: name
        run: |
          echo $GITHUB_OUTPUT
          echo age=34 >> $GITHUB_OUTPUT
      - run: echo ${{steps.name.outputs.age}}
      - run: echo $AGE
        env:
          AGE: 99
